server:
  port: 9091
  servlet:
    context-path: /pda/

spring:
  profiles:
    include: ws,redis
  datasource:
    ds1 :
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.108.251.176:3306/pda?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
      username: mysql
      password: 123456
    ds2 :
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://47.108.251.176:3306/pda-ydyh?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
      username: mysql
      password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.pda.api.mapper.*: debug

security :
  ignore :
    whites :
      - /login
      - /doc.html
