spring:
  redis:
    database: 0
    host: 192.168.130.189
    port: 6379
    password: zk-magic-cube-pwd-4afc
    lettuce:
      pool:
        max-active: 50 # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-wait: 10 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-idle: 20 # 连接池中的最大空闲连接 默认 8
        min-idle: 10 # 连接池中的最小空闲连接 默认 0