server:
  port: 9092
  servlet:
    context-path: /pda/

spring:
  profiles:
    include: ws,redis
  datasource:
    ds1 :
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@//192.168.61.15:1521/qmghis
      username: mobile
      password: mobile
    ds2 :
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://192.168.61.55:3306/pda-ydyh?serverTimezone=GMT%2B8&characterEncoding=utf8&useSSL=true
      username: ydyd
      password: ydyh123456
    ds3 :
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      url: jdbc:sqlserver://192.168.61.64:1433;databaseName=rmlis6
      username: sa
      password: ruimei
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
mybatis-plus:
  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
     log-impl : org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    com.pda.api.mapper.*: debug

security :
  ignore :
    whites :
      - /login
      - /doc.html
      - /webjars/
      - /swagger-resources
      - /v2/api-docs
      - /version/

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /system/notice/*
  # 匹配链接
  urlPatterns: /system/*,/monitor/*,/tool/*

cache :
  loginToken : 1
